services:
  backend:
    build:
      context: ./backend
    container_name: backend_user
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db1:5432/user-management
    depends_on:
      - db1

  frontend:
    build:
      context: ./frontend/user
    container_name: frontend_user
    ports:
      - "3000:3000"

  db1:
    image: postgres:15-alpine
    container_name: db1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user-management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
